// This is an autogenerated file from Firebase Studio.
'use server';
 
/**
 * @fileOverview Explains the user's EcoScore upon initial interaction with the EcoGPT Tutor.
 *
 * - ecoGptTutorInitialExplanation - A function that provides an explanation of the EcoScore.
 * - EcoGptTutorInitialExplanationInput - The input type for the ecoGptTutorInitialExplanation function.
 * - EcoGptTutorInitialExplanationOutput - The return type for the ecoGptTutorInitialExplanation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EcoGptTutorInitialExplanationInputSchema = z.object({
  ecoScore: z.number().describe('The user\u2019s current EcoScore.'),
  comparisonGroup: z.string().describe('The group to which the user is being compared (e.g., city, community).'),
  averageScore: z.number().describe('The average EcoScore for the comparison group.'),
});

export type EcoGptTutorInitialExplanationInput = z.infer<
  typeof EcoGptTutorInitialExplanationInputSchema
>;

const EcoGptTutorInitialExplanationOutputSchema = z.object({
  explanation: z.string().describe('A clear and concise explanation of the user\u2019s EcoScore, including how it compares to the average score of their comparison group.'),
});

export type EcoGptTutorInitialExplanationOutput = z.infer<
  typeof EcoGptTutorInitialExplanationOutputSchema
>;

export async function ecoGptTutorInitialExplanation(
  input: EcoGptTutorInitialExplanationInput
): Promise<EcoGptTutorInitialExplanationOutput> {
  return ecoGptTutorInitialExplanationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'ecoGptTutorInitialExplanationPrompt',
  input: {schema: EcoGptTutorInitialExplanationInputSchema},
  output: {schema: EcoGptTutorInitialExplanationOutputSchema},
  prompt: `You are an AI tutor designed to explain EcoScores to users. An EcoScore is a measure of a person's environmental impact.

  Explain the user's EcoScore in a clear and concise manner, comparing it to the average EcoScore of their comparison group.

  User's EcoScore: {{{ecoScore}}}
  Comparison Group: {{{comparisonGroup}}}
  Average EcoScore for Comparison Group: {{{averageScore}}}

  Explanation:`,
});

const ecoGptTutorInitialExplanationFlow = ai.defineFlow(
  {
    name: 'ecoGptTutorInitialExplanationFlow',
    inputSchema: EcoGptTutorInitialExplanationInputSchema,
    outputSchema: EcoGptTutorInitialExplanationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
